const {randomUUID,randomBytes,createHash}=require('node:crypto');
const PAID=['결제 완료','배송 준비','배송 중','배송 완료'];
const clean=(v,n=200)=>String(v??'').trim().slice(0,n);
const hash=v=>createHash('sha256').update(String(v)).digest('hex');
const day=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10);
class ValidationError extends Error{}
const defaults={storeName:'무드노트',email:'',phone:'',hours:'평일 10:00–17:00',description:'취향을 기록하는 문구 편집숍',shippingFee:3000,freeShippingThreshold:30000,dispatchDays:'결제 후 1–2영업일',carrier:'CJ대한통운'};
function integer(value,min,max,label){const n=Number(value);if(!Number.isSafeInteger(n)||n<min||n>max)throw new ValidationError(`${label} 값을 확인해주세요.`);return n;}
function imageURL(value){const s=clean(value,2000);if(/^assets\/[a-zA-Z0-9._/-]+$/.test(s)&&!s.includes('..'))return s;try{if(new URL(s).protocol==='https:')return s}catch{}throw new ValidationError('이미지는 assets 경로 또는 HTTPS 주소를 사용해주세요.');}
function couponDiscount(c,subtotal){if(!c?.enabled||c.startDate&&day()<c.startDate||c.endDate&&day()>c.endDate||subtotal<Number(c.minSpend||0))return 0;const raw=c.type==='percent'?Math.floor(subtotal*Number(c.value)/100):Number(c.value);return Math.max(0,Math.min(subtotal,raw,Number(c.maxDiscount)||subtotal));}
function grouped(items){const groups=new Map();for(const item of items){let p=groups.get(item.id);if(!p){p={quantity:0,variants:{}};groups.set(item.id,p)}p.quantity+=item.quantity;p.variants[item.option]=(p.variants[item.option]||0)+item.quantity;}return groups;}
function makeCommerce({db,FV,ErrorType,secret,fetchImpl=fetch}){
 const fail=(code,message)=>{throw new ErrorType(code,message)};
 const audit=(tx,actor,action,target,detail={})=>tx.set(db.collection('adminAudit').doc(),{actor:actor?.token?.email||'payment-server',action,target,...detail,createdAt:FV.serverTimestamp()});
 const owner=request=>{if(!request.auth?.token?.email_verified||request.auth.token.email!=='gogogen98@gmail.com')fail('permission-denied','운영자 권한이 필요합니다.');};
 const policy=async()=>({...defaults,...(await db.doc('storefront/public').get()).data()});
 async function api(path,body,key){let response;try{response=await fetchImpl('https://api.tosspayments.com/v1/payments/'+path,{method:body?'POST':'GET',headers:{Authorization:'Basic '+Buffer.from(secret()+':').toString('base64'),'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});}catch{fail('unavailable','결제사 응답을 확인하지 못했습니다. 재고는 보관되며 결제 상태 확인으로 다시 조회할 수 있습니다.');}const data=await response.json();return {ok:response.ok,status:response.status,data};}
 const usageRef=(code,uid)=>db.doc('couponUsage/'+hash(code+':'+uid));
 async function checkCoupon(code,uid,subtotal,tx=null){if(!code)return {discount:0,coupon:null};if(!uid)fail('unauthenticated','쿠폰은 로그인 후 사용할 수 있습니다.');const get=ref=>tx?tx.get(ref):ref.get();const snap=await get(db.doc('coupons/'+code)),coupon=snap.data();const discount=couponDiscount(coupon,subtotal);if(!discount)fail('failed-precondition','사용할 수 없는 쿠폰이거나 최소 구매금액을 충족하지 못했습니다.');const usage=await get(usageRef(code,uid));if(usage.exists&&['reserved','used'].includes(usage.data().status))fail('failed-precondition','이미 사용했거나 결제 중인 쿠폰입니다.');if(coupon.firstOrder){const prior=await get(db.collection('orders').where('userId','==',uid));if(prior.docs.some(d=>PAID.includes(d.data().status)||d.data().status==='승인 확인 중'))fail('failed-precondition','첫 주문 전용 쿠폰입니다.');}return {discount,coupon};}
 async function prepare(request){const data=request.data||{},requested=data.items;if(!Array.isArray(requested)||!requested.length||requested.length>50)fail('invalid-argument','주문 상품을 확인해주세요.');const items=[],seen=new Set();for(const row of requested){const id=clean(row.id,60);if(!/^[a-zA-Z0-9_-]+$/.test(id))fail('invalid-argument','상품 코드가 올바르지 않습니다.');const quantity=integer(row.quantity,1,99,'수량'),snap=await db.doc('products/'+id).get(),p=snap.data();if(!p||p.saleStatus!=='판매 중'||p.searchVisible===false)fail('failed-precondition','판매 중인 상품이 아닙니다.');const option=clean(row.option||p.options?.[0]||'기본 옵션',100);if(p.options?.length&&!p.options.includes(option))fail('invalid-argument','상품 옵션을 다시 선택해주세요.');const key=id+'|'+option;if(seen.has(key))fail('invalid-argument','중복 상품을 합쳐 주문해주세요.');seen.add(key);if(Number(p.stock)<quantity||(p.variantStock&&Number(p.variantStock[option]??0)<quantity))fail('failed-precondition',`${p.name}의 재고가 부족합니다.`);items.push({id,name:p.name,image:p.image,quantity,option,price:integer(p.price,1,10000000,'상품 가격')});}
  const subtotal=items.reduce((s,p)=>s+p.price*p.quantity,0),settings=await policy(),shipping=subtotal>=settings.freeShippingThreshold?0:settings.shippingFee,code=clean(data.couponCode,40).toUpperCase();if(code&&!/^[A-Z0-9_-]+$/.test(code))fail('invalid-argument','쿠폰 코드를 확인해주세요.');const {discount}=await checkCoupon(code,request.auth?.uid,subtotal),total=subtotal+shipping-discount;if(total<100)fail('failed-precondition','최소 결제금액은 100원입니다.');
  const customer=clean(data.customer,50),phone=clean(data.phone,30),email=clean(request.auth?.token?.email||data.email,160),a=data.address||{};if(!customer||!phone||!/^\S+@\S+\.\S+$/.test(email)||!clean(a.zip,10)||!clean(a.address,200))fail('invalid-argument','주문자와 배송지를 확인해주세요.');
  const id='MN'+day().replaceAll('-','').slice(2)+'-'+randomUUID().slice(0,12),guestAccessToken=request.auth?'':randomBytes(24).toString('hex');
  const order={id,userId:request.auth?.uid||null,userEmail:email,guest:!request.auth,guestAccessHash:guestAccessToken?hash(guestAccessToken):null,customer,phone,items,subtotal,shipping,discount,total,couponCode:code,payment:'toss',status:'결제 요청',inventoryState:'none',address:{zip:clean(a.zip,10),address:clean(a.address,200),address2:clean(a.address2,200),recipient:clean(a.recipient||customer,50),recipientPhone:clean(a.recipientPhone||phone,30),memo:clean(a.memo,300)},customText:clean(data.customText,100),customUploads:(Array.isArray(data.customUploads)?data.customUploads:[]).slice(0,5).map(f=>({name:clean(f.name,120),url:clean(f.url,2000)})),createdAt:FV.serverTimestamp(),updatedAt:FV.serverTimestamp()};await db.doc('orders/'+id).create(order);return {orderId:id,amount:total,discount,shipping,orderName:items[0].name+(items.length>1?` 외 ${items.length-1}건`:''),customerName:customer,customerEmail:email,guestAccessToken};
 }
 async function reserve(ref,key){return db.runTransaction(async tx=>{const snap=await tx.get(ref),order=snap.data();if(!order)fail('not-found','주문을 찾을 수 없습니다.');if(PAID.includes(order.status))return order;if(order.status!=='결제 요청'&&order.status!=='승인 확인 중')fail('failed-precondition','이 주문은 결제할 수 없습니다.');if(order.paymentKey&&order.paymentKey!==key)fail('failed-precondition','결제 키가 일치하지 않습니다.');if(order.inventoryState==='reserved')return order;
  const products=[];for(const [id,g] of grouped(order.items)){const target=db.doc('products/'+id),snap=await tx.get(target),p=snap.data();if(!p||p.saleStatus!=='판매 중'||Number(p.stock)<g.quantity)fail('failed-precondition','상품 재고가 부족합니다.');const variantStock=p.variantStock?{...p.variantStock}:null;if(variantStock)for(const [option,qty] of Object.entries(g.variants)){if(Number(variantStock[option]??0)<qty)fail('failed-precondition',`${option} 옵션 재고가 부족합니다.`);variantStock[option]-=qty;}products.push({target,stock:Number(p.stock)-g.quantity,variantStock});}
  const checked=await checkCoupon(order.couponCode,order.userId,order.subtotal,tx);if(checked.discount!==order.discount)fail('failed-precondition','쿠폰 조건이 변경되었습니다. 주문서를 다시 작성해주세요.');
  for(const p of products)tx.update(p.target,{stock:p.stock,...(p.variantStock?{variantStock:p.variantStock}:{}),updatedAt:FV.serverTimestamp()});
  if(order.couponCode)tx.set(usageRef(order.couponCode,order.userId),{code:order.couponCode,uid:order.userId,orderId:order.id,status:'reserved',updatedAt:FV.serverTimestamp()});
  tx.update(ref,{inventoryState:'reserved',status:'승인 확인 중',paymentKey:key,confirmKey:order.confirmKey||randomUUID(),updatedAt:FV.serverTimestamp()});return order;
 });}
 async function settle(ref,payment){return db.runTransaction(async tx=>{const order=(await tx.get(ref)).data();if(order.paymentKey!==payment.paymentKey||order.id!==payment.orderId||order.total!==payment.totalAmount)fail('failed-precondition','결제 정보가 주문과 일치하지 않습니다.');if(order.cancelRequest||order.status==='주문 취소')fail('failed-precondition','취소 처리 중인 주문입니다.');if(PAID.includes(order.status))return order;
  if(order.inventoryState!=='reserved')fail('failed-precondition','재고 예약을 확인할 수 없습니다.');const patch={status:'결제 완료',inventoryState:'committed',paymentMethod:payment.method||'토스페이먼츠',approvedAt:payment.approvedAt||null,receiptUrl:payment.receipt?.url||null,updatedAt:FV.serverTimestamp()};tx.update(ref,patch);if(order.couponCode)tx.set(usageRef(order.couponCode,order.userId),{code:order.couponCode,uid:order.userId,orderId:order.id,status:'used',discount:order.discount,updatedAt:FV.serverTimestamp()});audit(tx,null,'결제 승인',order.id);return {...order,...patch};});}
 async function release(ref,status,restock,actor,reason){return db.runTransaction(async tx=>{const order=(await tx.get(ref)).data();if(order.status===status&&['released','disposed','none'].includes(order.inventoryState))return order;const shouldRestore=restock&&['reserved','committed'].includes(order.inventoryState),updates=[];if(shouldRestore)for(const [id,g] of grouped(order.items)){const target=db.doc('products/'+id),p=(await tx.get(target)).data();if(!p)fail('failed-precondition','복원할 상품이 없어 재고 확인이 필요합니다.');let variants=p.variantStock?{...p.variantStock}:null;if(variants)for(const [option,qty] of Object.entries(g.variants)){variants[option]=Number(variants[option]||0)+qty;}updates.push({target,stock:Number(p.stock)+g.quantity,variants});}
  for(const p of updates)tx.update(p.target,{stock:p.stock,...(p.variants?{variantStock:p.variants}:{}),updatedAt:FV.serverTimestamp()});
  const patch={status,inventoryState:shouldRestore?'released':order.inventoryState==='committed'?'disposed':order.inventoryState||'none',...(status==='주문 취소'?{refundedAmount:order.total,claimStatus:'환불 완료'}:{}),lastReason:clean(reason,300),updatedAt:FV.serverTimestamp()};tx.update(ref,patch);if(order.couponCode)tx.set(usageRef(order.couponCode,order.userId),{uid:order.userId,code:order.couponCode,orderId:order.id,status:'released',updatedAt:FV.serverTimestamp()});audit(tx,actor,status,order.id,{restocked:shouldRestore});return {...order,...patch};});}
 const result=o=>({orderId:o.id,status:o.status,method:o.paymentMethod||'토스페이먼츠',receiptUrl:o.receiptUrl||null,guest:Boolean(o.guest)});
 async function confirm(request){const {orderId,paymentKey,guestToken}=request.data||{},amount=Number(request.data?.amount);if(!/^[A-Za-z0-9_-]{1,64}$/.test(orderId||'')||!paymentKey||paymentKey.length>200)fail('invalid-argument','결제 정보를 확인해주세요.');const ref=db.doc('orders/'+orderId),order=(await ref.get()).data();if(!order)fail('not-found','주문이 없습니다.');if(order.userId?order.userId!==request.auth?.uid:!guestToken||hash(guestToken)!==order.guestAccessHash)fail('permission-denied','주문 접근 권한이 없습니다.');if(order.total!==amount)fail('failed-precondition','결제 금액이 다릅니다.');if(PAID.includes(order.status))return result(order);await reserve(ref,paymentKey);const pending=(await ref.get()).data();
  let payment=await api(encodeURIComponent(paymentKey));if(payment.ok&&payment.data.status==='CANCELED'){await release(ref,'주문 취소',true,null,'결제사 취소 확인');fail('failed-precondition','이미 취소된 결제입니다.');}
  if(!payment.ok||payment.data.status!=='DONE')payment=await api('confirm',{paymentKey,orderId,amount},pending.confirmKey);
  if(!payment.ok){const query=await api(encodeURIComponent(paymentKey));if(query.ok&&query.data.status==='DONE')payment=query;else if(query.ok&&['ABORTED','EXPIRED','CANCELED'].includes(query.data.status)){await release(ref,query.data.status==='CANCELED'?'주문 취소':'결제 실패',true,null,'결제사 실패 확인');fail('failed-precondition',clean(payment.data.message,200)||'결제에 실패했습니다.');}else if(payment.status===400&&query.status===404&&!['ALREADY_PROCESSED_PAYMENT','IDEMPOTENT_REQUEST_PROCESSING','PROVIDER_ERROR','FAILED_INTERNAL_SYSTEM_PROCESSING'].includes(payment.data.code)){await release(ref,'결제 실패',true,null,'결제사 승인 거절');fail('failed-precondition',clean(payment.data.message,200)||'결제가 거절되었습니다.');}else fail('unavailable','결제 결과 확인이 필요합니다. 다시 확인하거나 고객센터로 문의해주세요.');}
  if(payment.data.status!=='DONE')fail('failed-precondition','결제가 아직 완료되지 않았습니다.');return result(await settle(ref,payment.data));
 }
 async function admin(request){owner(request);const d=request.data||{},action=d.action;
  if(action==='saveSettings'){const v=d.settings||{},settings={...defaults};for(const key of ['storeName','email','phone','hours','description','dispatchDays','carrier'])settings[key]=clean(v[key],key==='description'?300:120);settings.shippingFee=integer(v.shippingFee,0,100000,'배송비');settings.freeShippingThreshold=integer(v.freeShippingThreshold,0,10000000,'무료배송 기준');if(!settings.storeName)fail('invalid-argument','쇼핑몰명을 입력해주세요.');await db.runTransaction(async tx=>{tx.set(db.doc('storefront/public'),{...settings,updatedAt:FV.serverTimestamp()});audit(tx,request.auth,'운영 설정 저장','public');});return {ok:true};}
  if(action==='saveCoupon'){const v=d.coupon||{},code=clean(v.code,40).toUpperCase();if(!/^[A-Z0-9_-]{3,40}$/.test(code))fail('invalid-argument','쿠폰 코드는 영문·숫자·하이픈 3–40자로 입력해주세요.');const c={code,name:clean(v.name,80),type:v.type==='amount'?'amount':'percent',value:integer(v.value,1,v.type==='amount'?1000000:100,'할인'),minSpend:integer(v.minSpend||0,0,10000000,'최소 금액'),maxDiscount:integer(v.maxDiscount||0,0,1000000,'최대 할인'),firstOrder:!!v.firstOrder,enabled:!!v.enabled,startDate:clean(v.startDate,10),endDate:clean(v.endDate,10)};if(!c.name||![c.startDate,c.endDate].every(s=>/^\d{4}-\d{2}-\d{2}$/.test(s))||c.endDate<c.startDate)fail('invalid-argument','쿠폰 이름과 유효기간을 확인해주세요.');await db.runTransaction(async tx=>{tx.set(db.doc('coupons/'+code),{...c,updatedAt:FV.serverTimestamp()});audit(tx,request.auth,'쿠폰 저장',code);});return {ok:true};}
  if(action==='saveProduct'){const p=d.product||{},id=clean(p.id,60);if(!/^[a-z0-9-]+$/.test(id))fail('invalid-argument','상품 코드를 확인해주세요.');const options=(p.options||[]).map(o=>clean(o,100));if(!options.length||options.length>30||new Set(options).size!==options.length||options.some(o=>!o))fail('invalid-argument','옵션은 중복 없이 1–30개 입력해주세요.');const patch={id,name:clean(p.name,80),maker:clean(p.maker,40),category:p.category,price:integer(p.price,1,10000000,'가격'),originalPrice:integer(p.originalPrice||0,0,10000000,'정가'),stock:integer(p.stock,0,1000000,'재고'),saleStatus:p.saleStatus,badge:clean(p.badge,20),description:clean(p.description,180),detail:clean(p.detail,5000),image:imageURL(p.image),gallery:(p.gallery||[]).slice(0,12).map(g=>({src:imageURL(g.src),label:clean(g.label,100),note:clean(g.note,300)})),options,spec:Object.fromEntries(Object.entries(p.spec||{}).slice(0,30).map(([k,v])=>[clean(k,50),clean(v,300)])),searchVisible:!!p.searchVisible,featured:!!p.featured,reviewEnabled:!!p.reviewEnabled,qnaEnabled:!!p.qnaEnabled,updatedAt:FV.serverTimestamp()};if(!patch.name||!patch.maker||!['record','deco','custom','write','hobby','pouch','gift'].includes(p.category)||!['판매 중','판매 중지','품절'].includes(p.saleStatus))fail('invalid-argument','상품 필수 정보를 확인해주세요.');patch.variantStock=p.variantStock?Object.fromEntries(options.map(o=>[o,integer(p.variantStock[o],0,1000000,o+' 재고')])):null;if(patch.variantStock)patch.stock=Object.values(patch.variantStock).reduce((a,b)=>a+b,0);
   await db.runTransaction(async tx=>{const ref=db.doc('products/'+id),old=(await tx.get(ref)).data();if(d.create&&old)fail('already-exists','이미 있는 상품 코드입니다.');if(!d.create&&!old)fail('not-found','상품이 없습니다.');if(old&&d.expectedUpdatedAt&&old.updatedAt?.toMillis()!==d.expectedUpdatedAt)fail('aborted','다른 작업에서 재고 또는 상품이 변경되었습니다. 다시 열고 저장해주세요.');tx.set(ref,{...patch,...(!old?{createdAt:FV.serverTimestamp(),mood:'natural'}:{})},{merge:true});audit(tx,request.auth,old?'상품 수정':'상품 등록',id);});return {ok:true};}
  const id=clean(d.orderId,64);if(!/^[A-Za-z0-9_-]+$/.test(id))fail('invalid-argument','주문번호를 확인해주세요.');const ref=db.doc('orders/'+id),order=(await ref.get()).data();if(!order)fail('not-found','주문이 없습니다.');
  if(action==='reconcile'){if(!order.paymentKey)fail('failed-precondition','결제 시도가 없는 주문입니다.');const res=await api(encodeURIComponent(order.paymentKey));if(!res.ok)fail('unavailable','결제사에서 상태를 조회하지 못했습니다.');if(res.data.status==='DONE')return result(await settle(ref,res.data));if(['CANCELED','ABORTED','EXPIRED'].includes(res.data.status)){return result(await release(ref,res.data.status==='CANCELED'?'주문 취소':'결제 실패',order.cancelRequest?order.cancelRequest.restock:order.inventoryState==='reserved',request.auth,'결제사 상태 동기화'));}return {status:res.data.status,message:'결제사에서 아직 완료되지 않은 주문입니다.'};}
  if(action==='refund'){
   const reason=clean(d.reason,300);if(!reason)fail('invalid-argument','취소·환불 사유를 입력해주세요.');
   const operation=await db.runTransaction(async tx=>{const o=(await tx.get(ref)).data();if(o.status==='주문 취소')return null;if(!PAID.includes(o.status)&&o.status!=='승인 확인 중')fail('failed-precondition','결제 확인 후 환불할 수 있습니다.');if(!o.paymentKey)fail('failed-precondition','결제 키가 없어 토스 관리자 확인이 필요합니다.');if(o.cancelRequest)return o.cancelRequest;const op={id:randomUUID(),reason,restock:!!d.restock};tx.update(ref,{cancelRequest:op,updatedAt:FV.serverTimestamp()});audit(tx,request.auth,'환불 요청',id,{reason});return op;});if(!operation)return {status:'주문 취소'};
   let res=await api(encodeURIComponent(order.paymentKey));if(!res.ok)fail('unavailable','결제 확인 실패. 다시 환불을 실행하면 동일 요청을 확인합니다.');if(res.data.status!=='CANCELED')res=await api(encodeURIComponent(order.paymentKey)+'/cancel',{cancelReason:operation.reason},operation.id);
   if(!res.ok||res.data.status!=='CANCELED')fail('failed-precondition',clean(res.data.message,200)||'취소가 완료되지 않았습니다. 결제 상태를 다시 확인해주세요.');return result(await release(ref,'주문 취소',operation.restock,request.auth,operation.reason));
  }
  if(action==='updateOrder'){await db.runTransaction(async tx=>{const o=(await tx.get(ref)).data();if(o.cancelRequest)fail('failed-precondition','환불 요청 중에는 주문을 변경할 수 없습니다.');const patch={updatedAt:FV.serverTimestamp()};if(d.status){const allowed={'결제 완료':['배송 준비'],'배송 준비':['배송 중'],'배송 중':['배송 완료'],'배송 완료':[]};if(d.status!==o.status&&!allowed[o.status]?.includes(d.status))fail('failed-precondition','허용되지 않는 주문 상태 변경입니다.');if(d.status==='배송 중'&&(!clean(d.carrier||o.carrier)||!clean(d.trackingNumber||o.trackingNumber)))fail('invalid-argument','택배사와 송장번호를 입력해주세요.');patch.status=d.status;}
   if(d.carrier!==undefined)patch.carrier=clean(d.carrier,60);if(d.trackingNumber!==undefined){const v=clean(d.trackingNumber,60);if(v&&!/^[a-zA-Z0-9-]{4,60}$/.test(v))fail('invalid-argument','송장번호를 확인해주세요.');patch.trackingNumber=v;}if(d.memo!==undefined)patch.adminMemo=clean(d.memo,2000);if(d.claimStatus!==undefined){if(!['','반품 접수','회수 완료','교환 접수','교환 재발송','처리 종료'].includes(d.claimStatus))fail('invalid-argument','처리 상태를 확인해주세요.');patch.claimStatus=d.claimStatus;patch.claimReason=clean(d.claimReason,300);}tx.update(ref,patch);audit(tx,request.auth,'주문·배송 변경',id,{status:patch.status||o.status,claimStatus:patch.claimStatus||''});});return {ok:true};}
  fail('invalid-argument','지원하지 않는 작업입니다.');
 }
 async function review(request){if(!request.auth)fail('unauthenticated','로그인 후 리뷰를 작성해주세요.');const d=request.data||{},productId=clean(d.productId,60),orderId=clean(d.orderId,64);if(!/^[A-Za-z0-9_-]+$/.test(productId)||!/^[A-Za-z0-9_-]+$/.test(orderId))fail('invalid-argument','상품과 주문을 확인해주세요.');const id=hash(request.auth.uid+':'+orderId+':'+productId),target=db.doc('reviews/'+id);await db.runTransaction(async tx=>{const order=(await tx.get(db.doc('orders/'+orderId))).data(),product=(await tx.get(db.doc('products/'+productId))).data(),existing=await tx.get(target);if(!order||order.userId!==request.auth.uid||!PAID.includes(order.status)||!order.items.some(i=>i.id===productId))fail('permission-denied','결제한 상품만 리뷰를 작성할 수 있습니다.');if(!product||product.reviewEnabled===false)fail('failed-precondition','리뷰 작성이 중지된 상품입니다.');if(existing.exists)fail('already-exists','이 주문의 리뷰를 이미 작성했습니다.');const content=clean(d.text,2000);if(!content)fail('invalid-argument','리뷰 내용을 입력해주세요.');tx.create(target,{id,userId:request.auth.uid,orderId,productId,product:product.name,customer:clean(request.auth.token.name||'구매 고객',40),rating:integer(d.rating,1,5,'별점'),text:content,photo:false,image:'',reply:'',hidden:false,verifiedPurchase:true,createdAt:FV.serverTimestamp(),updatedAt:FV.serverTimestamp()});});return {reviewId:id};}
 return {prepare,confirm,admin,policy,checkCoupon,review};
}
module.exports={makeCommerce,couponDiscount,grouped,integer,defaults,PAID,ValidationError};
