const test=require('node:test'),assert=require('node:assert/strict');
const {makeCommerce,couponDiscount}=require('../functions/commerce');
class HttpsError extends Error{constructor(code,message){super(message);this.code=code}}
const owner={uid:'owner',token:{email:'gogogen98@gmail.com',email_verified:true}},member={uid:'member',token:{email:'buyer@example.test'}};
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
function harness(){
 const records=new Map([['products/pen',{name:'펜',image:'assets/pen.png',price:2000,stock:10,saleStatus:'판매 중',searchVisible:true,options:['빨강','파랑'],variantStock:{빨강:5,파랑:5}}]]),payments=new Map(),calls=[];let sequence=0,queue=Promise.resolve(),confirmCount=0,cancelCount=0,dropConfirm=false,failSettle=false;
 const snapshot=(path)=>({exists:records.has(path),id:path.split('/').pop(),data:()=>clone(records.get(path))});
 const doc=path=>({path,get:async()=>snapshot(path),create:async v=>{if(records.has(path))throw Error('exists');records.set(path,clone(v));},set:async(v,o)=>records.set(path,o?.merge?{...records.get(path),...clone(v)}:clone(v)),update:async v=>{records.set(path,{...records.get(path),...clone(v)})}});
 const collection=path=>({path,doc:id=>doc(path+'/'+(id||'auto'+ ++sequence)),where:(key,op,value)=>({path,key,value,get:async()=>({docs:[...records].filter(([k,v])=>k.startsWith(path+'/')&&v[key]===value).map(([k])=>snapshot(k))})})});
 const db={doc,collection,runTransaction:fn=>{const task=queue.then(async()=>{const writes=[];let wrote=false;const tx={create:(ref,v)=>{wrote=true;writes.push(()=>ref.create(v));},get:async ref=>{assert.equal(wrote,false,'all reads must precede writes');return ref.get();},set:(ref,v,o)=>{wrote=true;writes.push(()=>ref.set(v,o));},update:(ref,v)=>{wrote=true;if(failSettle&&v.inventoryState==='committed'){failSettle=false;throw Error('database temporarily unavailable');}writes.push(()=>ref.update(v));}};const result=await fn(tx);for(const write of writes)await write();return result;});queue=task.catch(()=>{});return task;}};
 const fetchImpl=async(url,options)=>{calls.push({url,options});const tail=url.split('/payments/')[1],body=options.body?JSON.parse(options.body):null;let p;if(tail==='confirm'){p=payments.get(body.paymentKey)||{orderId:body.orderId,totalAmount:body.amount,paymentKey:body.paymentKey,method:'카드'};if(p.status!=='DONE')confirmCount++;p.status='DONE';p.approvedAt=new Date().toISOString();payments.set(body.paymentKey,p);if(dropConfirm){dropConfirm=false;throw Error('network timeout');}}else if(tail.endsWith('/cancel')){p=payments.get(decodeURIComponent(tail.split('/')[0]));if(p.status!=='CANCELED')cancelCount++;p.status='CANCELED';}else p=payments.get(decodeURIComponent(tail));return {ok:!!p,status:p?200:404,json:async()=>clone(p||{code:'NOT_FOUND_PAYMENT'})};};
 const commerce=makeCommerce({db,FV:{serverTimestamp:()=>({seconds:Math.floor(Date.now()/1000)})},ErrorType:HttpsError,secret:()=> 'test-secret',fetchImpl});
 const payload={items:[{id:'pen',option:'빨강',quantity:2}],customer:'테스트',phone:'01000000000',email:'guest@example.test',address:{zip:'00000',address:'테스트 주소'}};
 const prepare=async(extra={},auth=member)=>commerce.prepare({auth,data:{...payload,...extra}});
 const confirm=async(order,auth=member)=>commerce.confirm({auth,data:{orderId:order.orderId,paymentKey:'pay-'+order.orderId,amount:order.amount,guestToken:order.guestAccessToken}});
 return {commerce,records,payments,calls,prepare,confirm,get confirms(){return confirmCount},get cancels(){return cancelCount},drop(){dropConfirm=true},failSettle(){failSettle=true}};
}
test('price and delivery policy are calculated by the server',async()=>{const h=harness();h.records.set('storefront/public',{shippingFee:2500,freeShippingThreshold:5000});const order=await h.prepare({items:[{id:'pen',option:'빨강',quantity:2,price:1}],total:1});assert.equal(order.amount,6500);assert.equal(h.records.get('orders/'+order.orderId).items[0].price,2000);});
test('duplicate approval reserves and deducts option stock exactly once',async()=>{const h=harness(),o=await h.prepare();await Promise.all([h.confirm(o),h.confirm(o)]);assert.equal(h.records.get('products/pen').stock,8);assert.equal(h.records.get('products/pen').variantStock.빨강,3);assert.equal(h.confirms,1);assert.equal(h.records.get('orders/'+o.orderId).inventoryState,'committed');});
test('concurrent purchases cannot oversell',async()=>{const h=harness(),a=await h.prepare({items:[{id:'pen',option:'빨강',quantity:4}]}),b=await h.prepare({items:[{id:'pen',option:'빨강',quantity:4}]});const results=await Promise.allSettled([h.confirm(a),h.confirm(b)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(h.records.get('products/pen').variantStock.빨강,1);});
test('unknown approval response keeps reserved stock and recovers without double charging',async()=>{const h=harness(),o=await h.prepare();h.drop();await assert.rejects(h.confirm(o),/응답/);assert.equal(h.records.get('products/pen').stock,8);assert.equal(h.records.get('orders/'+o.orderId).status,'승인 확인 중');await h.confirm(o);assert.equal(h.confirms,1);assert.equal(h.records.get('products/pen').stock,8);});
test('database failure after payment is recoverable',async()=>{const h=harness(),o=await h.prepare();h.failSettle();await assert.rejects(h.confirm(o),/database/);await h.confirm(o);assert.equal(h.confirms,1);assert.equal(h.records.get('orders/'+o.orderId).status,'결제 완료');});
test('full refund and retries restore stock exactly once',async()=>{const h=harness(),o=await h.prepare();await h.confirm(o);const request={auth:owner,data:{action:'refund',orderId:o.orderId,reason:'미발송 취소',restock:true}};await h.commerce.admin(request);await h.commerce.admin(request);assert.equal(h.records.get('products/pen').stock,10);assert.equal(h.records.get('products/pen').variantStock.빨강,5);assert.equal(h.cancels,1);assert.equal(h.records.get('orders/'+o.orderId).refundedAmount,o.amount);});
test('refund does not restore unsellable returns when unchecked',async()=>{const h=harness(),o=await h.prepare();await h.confirm(o);await h.commerce.admin({auth:owner,data:{action:'refund',orderId:o.orderId,reason:'사용된 반품',restock:false}});assert.equal(h.records.get('products/pen').stock,8);assert.equal(h.records.get('orders/'+o.orderId).inventoryState,'disposed');});
test('admin endpoint and guest order ownership are enforced',async()=>{const h=harness(),o=await h.prepare({},null);await assert.rejects(h.confirm({...o,guestAccessToken:'wrong'},null),e=>e.code==='permission-denied');await assert.rejects(h.commerce.admin({auth:member,data:{action:'updateOrder',orderId:o.orderId,status:'결제 완료'}}),e=>e.code==='permission-denied');await h.confirm(o,null);});
test('cannot mark unpaid order as paid or ship without tracking',async()=>{const h=harness(),o=await h.prepare();await assert.rejects(h.commerce.admin({auth:owner,data:{action:'updateOrder',orderId:o.orderId,status:'결제 완료'}}),/허용/);await h.confirm(o);await h.commerce.admin({auth:owner,data:{action:'updateOrder',orderId:o.orderId,status:'배송 준비'}});await assert.rejects(h.commerce.admin({auth:owner,data:{action:'updateOrder',orderId:o.orderId,status:'배송 중'}}),/송장/);await h.commerce.admin({auth:owner,data:{action:'updateOrder',orderId:o.orderId,status:'배송 중',carrier:'CJ',trackingNumber:'123456789'}});assert.equal(h.records.get('orders/'+o.orderId).status,'배송 중');});
test('coupon minimum, cap, first purchase and usage apply to real order totals',async()=>{const h=harness();h.records.set('coupons/WELCOME',{enabled:true,type:'percent',value:10,minSpend:3000,maxDiscount:300,firstOrder:true,startDate:'2020-01-01',endDate:'2099-12-31'});const o=await h.prepare({couponCode:'WELCOME'});assert.equal(o.discount,300);await h.confirm(o);await assert.rejects(h.prepare({couponCode:'WELCOME'}),/이미 사용/);await h.commerce.admin({auth:owner,data:{action:'refund',orderId:o.orderId,reason:'취소',restock:true}});const next=await h.prepare({couponCode:'WELCOME'});assert.equal(next.discount,300);});
test('invalid options and quantities are rejected',async()=>{const h=harness();await assert.rejects(h.prepare({items:[{id:'pen',option:'없는 색',quantity:1}]}),/옵션/);await assert.rejects(h.prepare({items:[{id:'pen',option:'빨강',quantity:1.1}]}),/수량/);});
test('coupon expiry and minimum cannot yield a discount',()=>{assert.equal(couponDiscount({enabled:true,endDate:'2000-01-01',type:'amount',value:1000},5000),0);assert.equal(couponDiscount({enabled:true,minSpend:10000,type:'percent',value:10},5000),0);});
test('product editor persists option stock, gallery and specification',async()=>{const h=harness();await h.commerce.admin({auth:owner,data:{action:'saveProduct',product:{id:'pen',name:'수정 펜',maker:'무드노트',category:'write',price:2100,stock:99,saleStatus:'판매 중',image:'assets/pen.png',options:['빨강','파랑'],variantStock:{빨강:3,파랑:7},gallery:[{src:'https://example.test/photo.png',label:'활용 예시'}],spec:{구성:'1개'},searchVisible:true,reviewEnabled:true,qnaEnabled:true}}});const p=h.records.get('products/pen');assert.equal(p.stock,10);assert.equal(p.gallery[0].label,'활용 예시');assert.equal(p.spec.구성,'1개');});
test('only a paid buyer can post a review, once per order and product',async()=>{const h=harness(),o=await h.prepare();const req={auth:member,data:{orderId:o.orderId,productId:'pen',rating:5,text:'구매 후 리뷰'}};await assert.rejects(h.commerce.review(req),e=>e.code==='permission-denied');await h.confirm(o);await h.commerce.review(req);await assert.rejects(h.commerce.review(req),e=>e.code==='already-exists');});
test('shipping settings reject negative fees and write an audit record',async()=>{const h=harness();await assert.rejects(h.commerce.admin({auth:owner,data:{action:'saveSettings',settings:{storeName:'무드노트',shippingFee:-1,freeShippingThreshold:30000}}}),/배송비/);await h.commerce.admin({auth:owner,data:{action:'saveSettings',settings:{storeName:'무드노트',shippingFee:2500,freeShippingThreshold:20000}}});assert.equal(h.records.get('storefront/public').shippingFee,2500);assert.equal([...h.records.keys()].filter(k=>k.startsWith('adminAudit/')).length,1);});
